### ISSUE TITLE
panic: syscall/js: Value.Call: property delete is not a function, got undefined

### ISSUE THREAD

**Issue by electricface** [gopherjs/vecty#244]
```
panic: syscall/js: Value.Call: property delete is not a function, got undefined wasm_exec.js:41:14
wasm_exec.js:41:14
goroutine 2 [running]: wasm_exec.js:41:14
syscall/js.Value.Call(0x7ff8000000000801, 0x50d1f, 0x6, 0x46c748, 0x1, 0x1, 0x54f320) wasm_exec.js:41:14
	/home/tp/applications/go/src/syscall/js/js.go:321 +0x86 wasm_exec.js:41:14
github.com/gopherjs/vecty.wrappedObject.Delete(...) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom_wasmjs_gopherjs.go:97 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).removeProperties(0x5b9c00, 0x55a460) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:305 +0xf wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileProperties(0x5b9c00, 0x55a460) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:218 +0xbe wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5b9c00, 0x55a460, 0x55a460, 0x181c000f, 0x1048000b) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:207 +0x3a wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x83380, 0x5b9c00, 0x83380, 0x55a460, 0x5b9c00, 0x85201, 0x5b6db8, 0x1, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:981 +0x15 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5b9ce0, 0x55a540, 0x547be8, 0x201801, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5b9ce0, 0x55a540, 0x55a540, 0x51d02, 0xb) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x83380, 0x5b9ce0, 0x83380, 0x55a540, 0x0, 0x5b6b01, 0x7ff80003000007fa, 0x5b6b00, 0xaaf5a8) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:981 +0x15 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5beee0, 0x55b420, 0x50bb7, 0x5, 0x85260) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.KeyedList.reconcile(0x5beee0, 0x0, 0x0, 0x5be2a0, 0x833c0, 0x55e100, 0x5b6d80, 0x1, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:708 +0x44 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5be2a0, 0x55a7e0, 0x4daca0, 0x1, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:467 +0x10d wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5be2a0, 0x55a7e0, 0x55a7e0, 0x100000000000001, 0x1048000b) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x83380, 0x5be2a0, 0x83380, 0x55a7e0, 0x5be2a0, 0x1, 0x0, 0x0, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:981 +0x15 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5be380, 0x55a8c0, 0x4dabe8, 0x184c0001, 0x7ff80003000007fc) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5be380, 0x55a8c0, 0x55a8c0, 0x1a4, 0x1048000b) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x83380, 0x5be380, 0x83380, 0x55a8c0, 0x5be380, 0x5c0201, 0x2, 0x2, 0x85260) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:981 +0x15 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5bee00, 0x55b340, 0x4dab40, 0x5a6f01, 0x82c80) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5bee00, 0x55b340, 0x55b340, 0x0, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.renderComponent(0xaaff98, 0x495d40, 0x831c0, 0x495d40, 0x5a6ea0, 0x4dab01, 0x5b6ba8, 0x7ff8000000000201, 0x51d02) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:1047 +0x1a wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x831c0, 0x5a6ea0, 0x831c0, 0x495d40, 0x5b6ba8, 0x1, 0x0, 0x0, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:985 +0x9 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5b16c0, 0x554460, 0x50bb7, 0x5, 0x85260) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.KeyedList.reconcile(0x5b16c0, 0x0, 0x0, 0x5a90a0, 0x833c0, 0x5510c0, 0x5b61a8, 0x1, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:708 +0x44 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5a90a0, 0x525dc0, 0x41fed8, 0x1, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:467 +0x10d wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5a90a0, 0x525dc0, 0x525dc0, 0x5b6178, 0xb) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x83380, 0x5a90a0, 0x83380, 0x525dc0, 0x5b6178, 0x1, 0x0, 0x0, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:981 +0x15 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5a9180, 0x525ea0, 0x41fdf8, 0x451701, 0x35ae0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5a9180, 0x525ea0, 0x525ea0, 0x450701, 0x1048000b) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.render(0x83380, 0x5a9180, 0x83380, 0x525ea0, 0x5a9180, 0x1, 0x0, 0x0, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:981 +0x15 wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcileChildren(0x5a9260, 0x54a000, 0x41f958, 0x5a8d01, 0x82c80) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:495 +0x7a wasm_exec.js:41:14
github.com/gopherjs/vecty.(*HTML).reconcile(0x5a9260, 0x54a000, 0x54a000, 0x0, 0x0) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:210 +0x36 wasm_exec.js:41:14
github.com/gopherjs/vecty.renderComponent(0x84480, 0x40a240, 0xaaf7a0, 0x40a240, 0x40a240, 0x0, 0x109e004b, 0xab56f8, 0x10dd0003) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:1047 +0x1a wasm_exec.js:41:14
github.com/gopherjs/vecty.(*batchRenderer).render(0x200f60, 0x409e9d13879c4113) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:878 +0x22 wasm_exec.js:41:14
github.com/gopherjs/vecty.requestAnimationFrame.func1(0x85260, 0x21a980, 0x5ac1f0, 0x1, 0x1, 0x426e0, 0x21a980) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom.go:1151 +0xb wasm_exec.js:41:14
github.com/gopherjs/vecty.funcOf.func1(0x0, 0x5990f8, 0x1, 0x1, 0x599001, 0x15b0a82e5dc95600) wasm_exec.js:41:14
	/home/tp/projects/gitlab/deepin-code-release-platform/frontend/src/github.com/gopherjs/vecty/dom_wasmjs_gopherjs.go:36 +0x15 wasm_exec.js:41:14
syscall/js.handleEvent() wasm_exec.js:41:14
	/home/tp/applications/go/src/syscall/js/func.go:90 +0x1d wasm_exec.js:41:14
```

**Comment by electricface** [comment]
browser is firefox 68.0
vecty commit: 2b6fc20f8913c7dadc6a67786be15c8c92bbd16a

**Comment by electricface** [comment]
wrappedObject.j is <span class="tag is-rounded is-success" title="15.11发布">

**Comment by marwan-at-work** [comment]
Getting the same error
